#include "pico/stdlib.h"
#include "hardware/clocks.h"
#include "hardware/pio.h"
#include <stdio.h>
#include "blink.pio.h" // autogenerated by pioasm

int main() {
    stdio_init_all();
    // Give USB serial time to connect
    sleep_ms(5000);

    const uint LED_PIN = PICO_DEFAULT_LED_PIN; // SparkFun Thing Plus RP2040: GPIO 25

    // Claim an unused PIO block
    PIO pio = pio_claim_unused_sm(pio0, false) != -1 ? pio0 :
              pio_claim_unused_sm(pio1, false) != -1 ? pio1 : NULL;
    if (pio == NULL) {
        printf("[ERROR] No free PIOs available\n");
        return 1;
    }

    // Claim an unused state machine
    int sm = pio_claim_unused_sm(pio, true);
    if (sm < 0) {
        printf("[ERROR] No free state machines available in selected PIO\n");
        return 1;
    }

    printf("[INFO] Using PIO %p, SM %d\n", pio, sm);

    // Load the program into the PIO
    uint offset = pio_add_program(pio, &hello_program);
    printf("[INFO] Program loaded at offset %d\n", offset);

    // Build a default configuration for our program
    pio_sm_config c = hello_program_get_default_config(offset);
    sm_config_set_out_pins(&c, LED_PIN, 1);
    pio_sm_set_consecutive_pindirs(pio, sm, LED_PIN, 1, true);
    pio_gpio_init(pio, LED_PIN);

    // Set PIO clock divider so SM frequency = 4000 Hz
    float sys_clk = clock_get_hz(clk_sys);
    float target_freq = 4000.0f;
    float clkdiv = sys_clk / target_freq;
    sm_config_set_clkdiv(&c, clkdiv);
    printf("[INFO] sys_clk=%.2f Hz, SM freq=%.2f Hz, clkdiv=%.2f\n",
           sys_clk, target_freq, clkdiv);

    // Initialize and enable the state machine
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_enabled(pio, sm, true);
    printf("[INFO] SM %d running on pin %d\n", sm, LED_PIN);


    while (true) {
        // Send 1 (LED on)
        pio_sm_put_blocking(pio, sm, 1);
        sleep_ms(500);

        // Send 0 (LED off)
        pio_sm_put_blocking(pio, sm, 0);
        sleep_ms(500);
    }

    return 0;
}